export const DEPARTMENTS = [
  {
    id:'multimedia', name:'เทคโนโลยีมัลติมีเดีย', tagline:'งานดิจิทัล หน้าจอ และสื่อโต้ตอบ',
    style:['Digital','Futuristic','Interactive','Modern','Dynamic'],
    subjects:[
      {label:'UI/UX', icon:'browser'},{label:'Website', icon:'browser'},{label:'Application', icon:'mobile'},
      {label:'Animation', icon:'film'},{label:'Motion Graphic', icon:'play'},{label:'3D', icon:'cube'},
      {label:'Digital Art', icon:'spark'},{label:'Interactive Media', icon:'layers'},{label:'Game', icon:'gamepad'},
      {label:'Digital Content', icon:'layers'},
    ],
    shapes:['Grid','Interface Frame','Geometric Elements','Particles','Digital Shapes','Motion Lines'],
    objects:['Screen','Smartphone','Computer','Controller','Mouse','Keyboard','UI Components'],
    shapesInferred:false,
  },
  {
    id:'interior', name:'ออกแบบภายใน', tagline:'พื้นที่ วัสดุ และบรรยากาศของห้อง',
    style:['Modern','Minimal','Japandi','Scandinavian','Industrial','Luxury'],
    subjects:[
      {label:'Interior', icon:'wall'},{label:'Room', icon:'wall'},{label:'House', icon:'wall'},
      {label:'Furniture', icon:'chair'},{label:'Lighting', icon:'lamp'},{label:'Wall', icon:'wall'},
      {label:'Floor', icon:'floor'},{label:'Ceiling', icon:'layout'},{label:'Material', icon:'material'},
      {label:'Moodboard', icon:'moodboard'},
    ],
    shapes:['ปริมาตรทรงสี่เหลี่ยม','เส้นสายเรียบง่าย','ผิวสัมผัสธรรมชาติ','องค์ประกอบโค้งมนแบบ Japandi'],
    objects:['Chair','Sofa','Table','Lamp','Cabinet','Curtain','Decorative Objects'],
    shapesInferred:false,
  },
  {
    id:'finearts', name:'ทัศนศิลป์', tagline:'งานศิลปะ การแสดงออก และองค์ประกอบภาพ',
    style:['Artistic','Expressive','Abstract','Experimental','Emotional'],
    subjects:[
      {label:'Painting', icon:'brush'},{label:'Drawing', icon:'canvas'},{label:'Sculpture', icon:'blob'},
      {label:'Illustration', icon:'brush'},{label:'Canvas', icon:'canvas'},{label:'Abstract Art', icon:'blob'},
      {label:'Mixed Media', icon:'scatter'},{label:'Experimental Art', icon:'spark'},
    ],
    shapes:['ฝีแปรงอิสระ','ทรงออร์แกนิก','พื้นผิวไม่สมมาตร','การซ้อนทับของชั้นสี'],
    objects:['Canvas','Paint Brush','Palette','Sculpture','Art Materials'],
    shapesInferred:false,
  },
  {
    id:'comdesign', name:'ออกแบบนิเทศศิลป์', tagline:'การสื่อสารด้วยภาพ ตัวอักษร และแบรนด์',
    style:['Graphic','Modern','Bold','Minimal','Structured','Communicative'],
    subjects:[
      {label:'Poster', icon:'poster'},{label:'Typography', icon:'type'},{label:'Logo', icon:'logo'},
      {label:'Branding', icon:'logo'},{label:'Packaging', icon:'package'},{label:'Editorial', icon:'editorial'},
      {label:'Infographic', icon:'chart'},{label:'Graphic Layout', icon:'layout'},{label:'Advertising', icon:'megaphone'},
    ],
    shapes:['กริดจัดวางที่ชัดเจน','บล็อกสีเรียบ','ตัวอักษรเป็นองค์ประกอบหลัก','เส้นแบ่งสัดส่วน'],
    objects:['Poster','Logo','Package','Magazine','Typography','Brand Identity'],
    shapesInferred:false,
  },
  {
    id:'architecture', name:'สถาปัตยกรรม', tagline:'อาคาร โครงสร้าง และการนำเสนอทางสถาปัตยกรรม',
    style:['Geometric','Modern','Architectural','Minimal','Structural'],
    subjects:[
      {label:'House', icon:'wall'},{label:'Building', icon:'building'},{label:'Architectural Model', icon:'cube'},
      {label:'Floor Plan', icon:'blueprint'},{label:'Elevation', icon:'layout'},{label:'Facade', icon:'building'},
      {label:'Structure', icon:'columns'},{label:'Architectural Board', icon:'moodboard'},{label:'3D Architecture', icon:'cube'},
    ],
    shapes:['เส้นโครงสร้างแนวตั้ง-นอน','บล็อกทรงเรขาคณิตเรียบ','ระนาบซ้อนชั้น','สัดส่วนแบบกริดสถาปัตย์'],
    objects:['Building','House','Architectural Model','Blueprint','Columns','Windows','Doors','Stairs'],
    shapesInferred:true,
  },
  {
    id:'urban', name:'ผังเมือง', tagline:'ระบบเมือง พื้นที่สาธารณะ และการวางผัง',
    style:['Urban','Functional','Systematic','Geographic','Sustainable'],
    subjects:[
      {label:'City Planning', icon:'city'},{label:'Master Plan', icon:'map'},{label:'Road Network', icon:'road'},
      {label:'Zoning', icon:'layout'},{label:'Map', icon:'map'},{label:'Public Space', icon:'park'},
      {label:'Urban Landscape', icon:'city'},{label:'Transportation', icon:'transport'},{label:'Sustainable City', icon:'park'},
    ],
    shapes:['โครงข่ายเส้นถนน','บล็อกผังพื้นที่','สัญลักษณ์แผนที่','โซนสีตามการใช้ที่ดิน'],
    objects:['City','Road','Map','Building Blocks','Park','Public Space','Transportation'],
    shapesInferred:true,
  },
  {
    id:'creative', name:'ออกแบบสร้างสรรค์', tagline:'ผลิตภัณฑ์ ต้นแบบ และงานออกแบบเชิงทดลอง',
    style:['Creative','Experimental','Innovative','Conceptual','Contemporary'],
    subjects:[
      {label:'Product Design', icon:'product'},{label:'Concept Design', icon:'spark'},{label:'Creative Object', icon:'blob'},
      {label:'Prototype', icon:'product'},{label:'Installation', icon:'install'},{label:'Innovative Design', icon:'spark'},
      {label:'Experimental Design', icon:'scatter'},
    ],
    shapes:['ทรงอิสระนอกกรอบเดิม','ชิ้นส่วนประกอบทดลอง','พื้นผิวผสมวัสดุ','องค์ประกอบต้นแบบ'],
    objects:['Product','Prototype','Sculpture','Creative Object','Installation','Experimental Materials'],
    shapesInferred:true,
  },
];
